from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from contextlib import asynccontextmanager
from db.mongo import db
from config import settings
from routers import processing, archive, agents
from fastapi.staticfiles import StaticFiles
from slowapi import _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from limiter import limiter
import os
import asyncio

# Create uploads directory if it doesn't exist
os.makedirs("uploads", exist_ok=True)

@asynccontextmanager
async def lifespan(app: FastAPI):
    await db.connect_to_database()
    yield
    await db.close_database_connection()

app = FastAPI(title=settings.APP_NAME, lifespan=lifespan)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

from fastapi.middleware.cors import CORSMiddleware

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://192.168.56.1:3000"
    ],
    allow_origin_regex=r"https://.*\.vercel\.app",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    return {"message": "Welcome to Heritix API"}

@app.get("/uploads/{filename}")
async def get_upload_file(filename: str):
    file_path = os.path.join("uploads", filename)
    
    # Check if the file needs TTS generation.
    # We generate TTS if:
    # 1. The file doesn't exist on disk, OR
    # 2. The file is a dummy beep file (size of 88244 bytes, or explicitly contains test_audio).
    needs_tts = False
    if not os.path.exists(file_path):
        needs_tts = True
    else:
        try:
            if os.path.getsize(file_path) == 88244 or "test_audio.wav" in filename:
                needs_tts = True
        except Exception:
            pass
            
    if needs_tts:
        try:
            # Query MongoDB for this filename
            doc = await db.db.knowledge.find_one({
                "$or": [
                    {"audio_url": {"$regex": filename}},
                    {"original_filename": filename}
                ]
            })
            if doc and doc.get("transcript"):
                transcript = doc["transcript"]
                lang = doc.get("detected_language", "en")
                
                from gtts import gTTS
                from gtts.lang import tts_langs
                
                supported = tts_langs()
                if lang not in supported:
                    lang = "en"
                    
                def generate_tts():
                    tts = gTTS(text=transcript, lang=lang)
                    tts.save(file_path)
                    
                await asyncio.to_thread(generate_tts)
        except Exception as e:
            print(f"Error generating TTS for {filename}: {e}")
            
    if os.path.exists(file_path):
        # Read header to determine if it is an MP3 file (generated by gTTS)
        try:
            with open(file_path, "rb") as f:
                header = f.read(3)
            if header.startswith(b"ID3") or (len(header) >= 2 and header[0] == 0xff and (header[1] & 0xf0) == 0xf0):
                return FileResponse(file_path, media_type="audio/mpeg")
        except Exception:
            pass
        return FileResponse(file_path)
    
    # Fallback to sample/test audio if the file is not on disk (e.g. database shared across devices)
    fallback_options = [
        "test_audio.wav",
        os.path.join("uploads", "b4621972-4083-404f-8fd5-35dd0ab27047_recording.wav"),
        os.path.join("uploads", "6d16389b-4392-4e53-ab85-e2a90143e322_recording.wav"),
        os.path.join("uploads", "34dcc28d-f458-48f5-b43e-63beec65ce80_recording.webm")
    ]
    for opt in fallback_options:
        if os.path.exists(opt):
            return FileResponse(opt)
            
    raise HTTPException(status_code=404, detail="File not found")

app.include_router(processing.router, prefix="/api", tags=["Processing"])
app.include_router(archive.router, prefix="/archive", tags=["Archive"])
app.include_router(agents.router, prefix="/agents", tags=["Agents"])

